version: '3'
services:
        web:
                image: flask_blewupflask_v1
                build: .
                ports:
                        - "8135:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
